//GETTERS
export const JOKES='GET_JOKES';
export const ONE_JOKE='GET_ONE_JOKE';
export const SEARCH_STRING='GET_SEARCH_STRING';
export const LOADING_STATUS='LOADING_STATUS';
export const ERRORS='ERRORS';
export const PAGINATED_JOKES='PAGINATED_JOKES';
export const FILTERED_PAGINATED_JOKES='FILTERED_PAGINATED_JOKES';

//MUTATIONS
export const SET_JOKES='SET_JOKES';
export const SET_JOKE='SET_JOKE';
export const SET_SEARCH_STRING='SET_SEARCH_STRING';
export const CHANGE_LOADING_STATUS='CHANGE_LOADING_STATUS';
export const SET_ERRORS='SET_ERRORS';
export const PAGINATE_JOKES='PAGINATE_JOKES';
export const SEARCH_JOKE='SEARCH_JOKE';
export const FILTER_PAGINATED_DATA='FILTER_PAGINATED_DATA';

//ACTIONS
export const GET_JOKES='GET_JOKES_FROM_API';
export const GET_ONE_JOKE='GET_ONE_JOKE_FROM_API';
